### ISSUE TITLE
Notice: Undefined variable: forum_user

### ISSUE THREAD

**Issue by ashcs** [dimkalinux/Fancy-Extensions#1]
Notice: Undefined variable: forum_user in .../forum/include/parser.php(25) : eval()'d code on line 11

Проблема в манифесте, в хуке ps_start происходит попытка подключения файла локализации. В глобальном контексте проблем нет, но если парсер подключается в функции где forum_user не определяется глобально, то возникает это предупреждение. 
При этом к локализации в парсере нигде нет обращения, т.е. блок кода 
            `if (!isset($fancy_video_tag)) {
                if ($forum_user['language'] != 'English' && file_exists($ext_info['path'].'/lang/'.$forum_user['language'].'/lang.php')) {
                    require $ext_info['path'].'/lang/'.$forum_user['language'].'/lang.php';
                } else {
                    require $ext_info['path'].'/lang/English/lang.php';
                }
            }`
инжектируемый в парсер - лишний.
Его надо либо убрать ( я убирал, работоспособность не изменилась, и нотисы исчезли), либо определить доступ через $GLOBALS

**Comment by dimkalinux** [comment]
@ashcs проверь, пожалуйста, что ошибка не воспроизводится в версии 0.4.11.
